---
- name: install, start and enable vsftpd
  gather_facts: no
  hosts: all
  tasks:
  - name: install vsftpd
    yum:
      name: vsftpd
      state: latest
  - name: start and enable vsftpd
    service: 
      name: vsftpd
      state: started
      enabled: yes
  - name: enable firewall on vsftpd
    firewalld:
#use ftp instead of vsftpd,ftp is the service name in firewalld; see firewall-cmd --get-services    
      service: ftp
      permanent: yes
      state: enabled
      immediate: yes
      
