---
- name: copy custom facts
  hosts: ansible1
  tasks:
  - name: create custom facts directory
    file: 
      state: directory
      recurse: yes
      path: /etc/ansible/facts.d
  - name: copy the custom facts
    copy:
      src: custom.fact
      dest: /etc/ansible/facts.d
